acl horario_laboral time SMTWHFA 08:00-23:00
acl miredlocalDMZ src "/etc/squid/conf.d/maquinas_permitidas.txt"
acl maquinas_prohibidas src "/etc/squid/conf.d/maquinas_prohibidas.txt"
acl sitios_bloqueados_http dstdomain "/etc/squid/conf.d/sitios_prohibidos.txt"
acl sitios_bloqueados_https ssl::server_name "/etc/squid/conf.d/sitios_prohibidos.txt"

ssl_bump terminate step1 sitios_bloqueados_https
ssl_bump peek step1
ssl_bump bump all

http_access deny maquinas_prohibidas
http_access deny sitios_bloqueados_http
http_access deny sitios_bloqueados_https
http_access allow miredlocalDMZ horario_laboral
http_access deny all
